### ISSUE TITLE
Non-standard characters break file naming

### ISSUE THREAD

**Issue by bjnoel** [rob-luke/emails-html-to-pdf#1]
I setup a forward to move my html only emails to an email address that this script processes. The colon in the subject line (Fwd:) breaks the file naming because files cannot contain non-standard characters, the file is saved simply as "Fwd".

**Comment by rob-luke** [comment]
Ah damnit. Good catch. Would it be ok just to remove these non-standard characters? Are there any additional characters to `:` that we should consider?

**Comment by bjnoel** [comment]
I think: \/*?:"<>|

**Comment by rob-luke** [comment]
I think this is now fixed. Could you please confirm

**Comment by smseidl** [comment]
@rob-luke - I had some yesterday that did not work... examples:
"Your statement is available – Reference: 4564944U06218667" - I think this has the long dash in it.  It created a noname pdf file.

**Comment by rob-luke** [comment]
Amazing work with that PR @smseidl 🎉 

I will close this issue, but please reopen if anyone is still having issues.
