### ISSUE TITLE
Errorhandling of Tracking Pixels

### ISSUE THREAD

**Issue by mirisbowring** [rob-luke/emails-html-to-pdf#11]
I've found another edge case:

I started converting my PayPal EMails to PDFs to import them to paperless.
for most of them i get the `HostNotFoundError`.
This relates to the tracking pixel in their mails.

How did I fix this?:
1. append `127.0.0.1 tracking.paypal.com` to `/etc/hosts`
2. pass pdfkit options to `pdfkit.from_string`:
```
options = {
    'load-media-error-handling': 'ignore'
}
pdfkit.from_string(pdftext, filename, options=options)
```

**Comment by smseidl** [comment]
This is the same issue I was having.  Has the most recent release fixed it for you?

**Comment by mirisbowring** [comment]
@smseidl I pulled the latest image today which did not solve the problem, which is why i created #12 :)
