### ISSUE TITLE
Option to activte or deactivate SSL/TLS and define the port via environment variables on docker

### ISSUE THREAD

**Issue by gsusxx** [rob-luke/emails-html-to-pdf#13]
Hey there, thanks for your effort!
Is it possible to setup the docker-compose.yml variables to define if SSL/TLS os in or off and another option to define the port that should be used?

**Comment by rob-luke** [comment]
Good idea, will do in the next round of fixes. Or open to a PR in the meantime.

**Comment by rob-luke** [comment]
I hope this has been addressed in #16, let me know if not. But I will close the issue in the meantime. Thanks for the suggestion.
