### ISSUE TITLE
Use Docker and Github Tags for releases

### ISSUE THREAD

**Issue by mirisbowring** [rob-luke/emails-html-to-pdf#19]
Hi,

since this project got some good improvements over the last days, the image should be shipped with a versioning system.
Since only the latest Tag is currently used, clients will not pull a later image because the tag name did not change.

My Recommendation:
* create a Github Release (Tag) for every new Feature / Group of Features
* Modify the Buildprocess to get triggered by the "onTag" action of GitHub and use the tagname as Docker tag
* Build the latest tag with the current master (independently of current releases) branch.

**Comment by rob-luke** [comment]
Agreed, I’ve been thinking the same thing. I’ll set it up in the coming days. Thanks for the suggestion.

**Comment by rob-luke** [comment]
Done in ea49a49b1460d712af8def0306a86753daddd218
