### ISSUE TITLE
[Feature Request] - allow for 60 second query of mailbox to be configurable

### ISSUE THREAD

**Issue by smseidl** [rob-luke/emails-html-to-pdf#3]
I don't need to pound my email with lookups ever minute.  Can you please add the ability to override this in the yaml file or else where?

**Comment by rob-luke** [comment]
Good idea. Will do

**Comment by rob-luke** [comment]
@smseidl let me know if this fixes your issue

**Comment by smseidl** [comment]
@rob-luke  Yes it fixed the issue, but caused a new one if I didn't update my yml file.  Maybe have a default set somewhere if not set in yaml?
