### ISSUE TITLE
Possible to add the email header to the PDF?

### ISSUE THREAD

**Issue by Cantello** [rob-luke/emails-html-to-pdf#33]
This looks perfect in combination with paperless, thanks for spending your time creating this!

Sometimes, I do not only get HTML emails but simply text emails where I would need the actual headers (from, date, subject, etc.) - is it possible to include these in the generated PDF?WKHTMLTOPDF options appear to control the PDF's layout, not the content.

**Comment by Cantello** [comment]
Ugh, just saw that this was already listed here: https://github.com/rob-luke/emails-html-to-pdf/issues/27

Please dismiss this issue.

**Comment by rob-luke** [comment]
Thanks for posting still. Make sure to thumbs up the other issue.
